captainVersion: 4
services:
    $$cap_appname-fusionauth:
        image: fusionauth/fusionauth-app:$$cap_fusionauth_version
        environment:
            DATABASE_URL: jdbc:$$cap_pg_host
            DATABASE_ROOT_USERNAME: $$cap_pg_user
            DATABASE_ROOT_PASSWORD: $$cap_pg_pass
            DATABASE_USERNAME: $$cap_pg_user
            DATABASE_PASSWORD: $$cap_pg_pass
            FUSIONAUTH_APP_MEMORY: $$cap_fusion_memory
            # SEARCH_SERVERS: http://srv-captain--$$cap_appname-elasticsearch:$$cap_container_search_port
            # FUSIONAUTH_APP_URL: http://srv-captain--$$cap_appname-fusionauth:$$cap_container_port
            SEARCH_TYPE: database
        restart: unless-stopped
        volumes:
            - $$cap_appname-fusionauth-config:/usr/local/fusionauth/config
        caproverExtra:
            containerHttpPort: $$cap_container_port
caproverOneClickApp:
    variables:
        - id: $$cap_fusionauth_version
          label: FusionAuth Version
          defaultValue: 1.42.0
          description: 'See tags at: https://hub.docker.com/r/fusionauth/fusionauth-app/tags'
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_fusion_memory
          label: Fusion Memory
          defaultValue: 512M
          description: ''
          validRegex: /^([a-zA-Z0-9])+$/
        - id: $$cap_container_port
          label: Container TCP Port
          defaultValue: '9011'
          description: Internal port for Fusion Auth container to listens to.
          validRegex: /^([0-9])+$/
        - id: $$cap_container_search_port
          label: Container TCP Port
          defaultValue: '9200'
          description: Internal port for Elasticsearch the container listens to.
          validRegex: /^([0-9])+$/
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: 13.7
          description: Choose the latest version of Postgres from https://hub.docker.com/_/postgres?tab=tags
        - id: $$cap_pg_user
          label: Postgres Username
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_pg_pass
          label: Postgres Password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_pg_db
          label: Postgres Default Database
          defaultValue: 'fusionauth'
          description: ''
          validRegex: /.{1,}/
    instructions:
        start: >-
            FusionAuth is a modern platform for Customer Identity and Access Management (CIAM). FusionAuth provides APIs and a responsive web user interface to support login, registration, localized email, multi-factor authentication, reporting and much more. See: https://fusionauth.io/docs/v1/tech/getting-started/ and https://github.com/FusionAuth/fusionauth-containers
        end: FusionAuth is deployed and available as srv-captain--$$cap_appname-fusionauth:$$cap_container_port to other apps
    displayName: FusionAuth v2
    isOfficial: false
    description: FusionAuth is a scalable, identity and user management platform built for devs
    documentation: 'Adapted from: https://fusionauth.io/docs/v1/tech/installation-guide/docker'