captainVersion: 4
services:
    $$cap_appname:
        image: nhost/hasura-storage:$$cap_version
        restart: always
        environment:
            DEBUG: "true"
            HASURA_METADATA: 1
            HASURA_ENDPOINT: $cap_hasura_endpoint
            HASURA_GRAPHQL_ADMIN_SECRET: $$cap_admin_secret
            S3_ENDPOINT: $cap_s3_endpoint
            S3_ACCESS_KEY: $cap_s3_access_key
            S3_SECRET_KEY: $cap_s3_secret_key
            S3_BUCKET: $cap_s3_bucket
            S3_ROOT_FOLDER: $cap_s3_root_folder
            POSTGRES_MIGRATIONS: 1
            POSTGRES_MIGRATIONS_SOURCE: $$cap_database_url
        caproverExtra:
            containerHttpPort: '8000'
caproverOneClickApp:
    variables:
        - defaultValue: 0.3.6
          description: Check out their docker hub for latest release https://hub.docker.com/r/nhost/hasura-storage/tags
          id: $$cap_version
          label: Hasura Storage Version
          validRegex: /^([^\s^\/])+$/
        - description: The admin secret gives you access to the console.
          id: $$cap_admin_secret
          label: Hasura admin secret(password)
          validRegex: /^(?=.*\d).{10,}$/
        - id: $$cap_database_url
          label: Postgres Connection URL
          description: postgres://username:password@host/database
          validRegex: /postgres://.+/.+/
        - id: $cap_hasura_endpoint
          label: Hasura Endpoint
          description: http://hasura.example.com
        - id: $cap_s3_endpoint
          label: S3 Endpoint
          description: http://s3.example.com
        - id: $cap_s3_access_key
          label: S3 Access Key
          description: S3 Access Key
        - id: $cap_s3_secret_key
          label: S3 Secret Key
          description: S3 Secret Key
        - id: $cap_s3_bucket
          label: S3 Bucket
          description: S3 Bucket
        - id: $cap_s3_root_folder
          label: S3 Root Folder
          description: S3 Root Folder
    instructions:
        end: >
            Hasura Storage by Nhost is deployed and available as $$cap_appname.
        start: Storage for Hasura GraphQL Engine
    displayName: Hasura Storage by Nhost
    isOfficial: false
    description: Storage for Hasura GraphQL Engine
    documentation: Hasura Storage by Nhost